export const CAMPAIGN_STATUS = {
	PENDING: "PENDING",
	IN_PROGRESS: "IN_PROGRESS",
	PAID: "PAID",
	COMPLETED: "COMPLETED"
};

export const CAMPAIGN_CREATOR_STATUS = {
	PENDING: "PENDING",
	INVITED: "INVITED",
	ACCEPTED: "ACCEPTED",
	COMPLETED: "COMPLETED"
};
